# Generated by Django 5.2.9 on 2026-07-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g. CEO at TechCorp, Senior Developer, Client', max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Optional: Used to send automatic thank-you note', max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Approve to display on frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
