# Generated by Django 5.2.9 on 2026-07-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(db_index=True, default=5, help_text='Rating from 1 to 5 stars'),
        ),
    ]
